### ISSUE TITLE
Passphrase required exception

### ISSUE THREAD

**Issue by jeffreysham** [googlesamples/android-credentials#38]
Hi,

I'm trying to test out smart lock to see if I should start using it in my app. I cloned the project and ran the credentials-signin project on my phone, but when I try to save a new credential, I get the following error. I looked the error code up and it is the error code for [resolution required](https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes.html#RESOLUTION_REQUIRED)

```
save:FAILURE
com.google.android.gms.common.api.ApiException: 6: Passphrase required.
  at com.google.android.gms.common.internal.zzb.zzy(Unknown Source:14)
  at com.google.android.gms.common.internal.zzbk.zzz(Unknown Source:0)
  at com.google.android.gms.common.internal.zzbl.zzr(Unknown Source:32)
  at com.google.android.gms.common.api.internal.BasePendingResult.zzc(Unknown Source:46)
  at com.google.android.gms.common.api.internal.BasePendingResult.setResult(Unknown Source:42)
  at com.google.android.gms.internal.zzavw.setResult(Unknown Source:2)
  at com.google.android.gms.internal.zzavv.zze(Unknown Source:2)
  at com.google.android.gms.internal.zzawc.onTransact(Unknown Source:46)
  at android.os.Binder.execTransact(Binder.java:682)
```

So, I was wondering why this error was happening and how to resolve it. After looking at the saveCredential(), it seems like the exception should've been an instance of `ResolvableApiException`.

Thanks,
Jeffrey

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
